### ISSUE TITLE
Right Arm not animating in ALS Default Overlay. 

### ISSUE THREAD

**Issue by Speelo** [tuatec/TTToolbox#15]
Hello, my Manny's right arm is not being animated when in the Default Overlay with the ALS system. I am using [dyanikoglu's ALS-Community](https://github.com/dyanikoglu/ALS-Community) version of the Plugin. I also used your Plugin and followed along with the Editor Utility Blueprint parts. As far as I understand the Skeleton's are the same and thats pretty much all we've been working with at this point.

Mantling is awesome, Rifle Overlay and Pistol Overlays are good. I was thinking this is in the constraints but all the Animations look good on their own. I am unsure if this is an IK issue happening somewhere in the Community verson?

I followed along with the basic version of ALSv4 from the Marketplace and same thing. The right arm is not animated.

[In this video](https://youtu.be/kZvDXwKMwAU), I demonstrate my issue. I have completed up to [Episode #11.0](https://youtu.be/yxjjbZDewo8).

**Comment by AchimTuran** [comment]
Ah that's your issue... I'm almost pretty sure that your anim curves got messed up from the overlay states. Sadly that is an unreal engine bug that is present since UE4. 🙈

Here might be your fix. https://youtu.be/Bp20Q436RpM

In case you don't want to code it yourself you can use the official release of TTToolbox v0.3.

Let me know if it worked for you, so we can close this issue here. If you step into new issues, do not hesitate to ask your questions here I read from time to time here and answer questions. What might also help is taking a look at the closed issues here on GitHub or in comments below on my YouTube videos. There we already also solved some questions.

**Comment by Speelo** [comment]
Ohh okay, I apologize for asking early. Probably should have just kept going. Its just you show the ending results at the end and so far mine isnt matching

**Comment by AchimTuran** [comment]
Did you get it working now? Oh it's fine, it's still a very complicated topic with lots of small details. Furthermore, we step into engine issues ... :-)

**Comment by daneweisman** [comment]
Just chiming in that I am also having this same issue with a metahuman retargeted to ALS. All other fixes recommended in the tutorials have worked so far but the arm is the last thing that is still unresolved. I tried fixing the anim curves one by one in the retargetted animations using TTCopyAllCurves, and added the missing curves to the metahuman base skeleton. This fixed some other issues but not the arm unfortunately.

Appreciate your efforts on this tool!

**Comment by AchimTuran** [comment]
Aye! Overlay state anim sequences are the main part when it comes to anim curves.

Thank you guys really appreciate that you like my work and tutorials. Soon I will make an entire series about Metahumans. Found some pretty neat parts that will make our life's easier when it comes to Metahuman retargeting. 😉

As the issue seems to be solved I will close this one here. 

If you guys step into further issues, do not hesitate to open a new one here.

All the success to your character integration journeys. 😉
