### ISSUE TITLE
Additive Base Pose Issue

### ISSUE THREAD

**Issue by sooroosh10** [tuatec/TTToolbox#3]
hi. when I add virtual bones to the ue5 SK_Mannequin, the skeleton changes to something strange. I also added Sockets and Constraints.
I have checked every bone name and every thing seems to be OK. It is in lyra. When I remove the virtual bones the skeleton gets fixed and there would be no problems.

![02](https://user-images.githubusercontent.com/48104594/173542451-83fcc625-2f5b-4769-9b42-becf38127374.png)

![01](https://user-images.githubusercontent.com/48104594/173542705-810bf3f8-0950-46ae-8b3c-d3f7768df1bb.png)

**Comment by sooroosh10** [comment]
I have watched this video "https://youtu.be/_hWs1Oj_6iE " and I have followed the exact steps you have described. Until that point everything is working grate. but when I add virtual bones the ue5 SK_Mannequin falls apart and when I delete virtual bones every thing works fine again. I have even Copied and pasted your codes in C++. I have checked all the virtual bones names. they are all the exact same. I don't know what else I need to do.

**Comment by AchimTuran** [comment]
Hmmm... sadly I don't know what is going wrong. I would need to have a look at the project myself.

Could you upload it somewhere?

**Comment by AchimTuran** [comment]
Sadly I did not get any response, consequently I can not help.

To me it look likes that the additive base pose animations are not set correctly.
https://youtu.be/_hWs1Oj_6iE
```
Fix additive animations
==============================
LeanPose_0 = Run_BasePose
LocoDetail_Accel* = Run_BasePose
*Look_F_Sweep = *N_Pose
Aim_Sweep = Pose_NoCurves
```

@sooroosh10 
If you come back to this issue and it is still present. Do not hesitate to reopen this issue. ;-)

**Comment by sooroosh10** [comment]
Hi. sorry to respond so late. I have uploaded the project's zip file on
google drive. I really appreciate if you would take a look at it.
This is the address:
https://drive.google.com/file/d/19CqjOsvuGgUp5dqtoAQ4uAn8XWN0J_aS/view?usp=sharing
best regards.
Farzami Sooroosh.

**Comment by sooroosh10** [comment]
I've shared an item with you:

MyProject2.rar
https://drive.google.com/file/d/19CqjOsvuGgUp5dqtoAQ4uAn8XWN0J_aS/view?usp=sharing&invite=CNKH86oE&ts=62b87788

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by AchimTuran** [comment]
@sooroosh10 
Sorry for the late response but I was very busy during the last days. Furthermore, thank you for providing the project!

I got it working! 👍 
![grafik](https://user-images.githubusercontent.com/6927011/176977749-e928df81-6d54-41e7-b107-95362b5a89b1.png)

Like I have written [here](https://github.com/tuatec/TTToolbox/issues/3#issuecomment-1156805224) you need to check all animations and see if there is a additive base pose not set. 😉 

Use the filter `FMI_ALS` and `Animation Sequence`.
![grafik](https://user-images.githubusercontent.com/6927011/176977828-e07b5e38-2579-4c51-b797-9c5f059d8179.png)
Sadly this additive animation is also not set.
![grafik](https://user-images.githubusercontent.com/6927011/176977846-f4f55483-1b7d-4714-b1f9-90116d88a910.png)

These one as well.
![grafik](https://user-images.githubusercontent.com/6927011/176977854-0fff1b45-f686-4401-8173-294253ce00a9.png)
![grafik](https://user-images.githubusercontent.com/6927011/176977863-7f29d441-012a-49a4-a087-df99e63b7574.png)

If you have further issues related to additive base pose, feel free to reopen the issue here. 😉

**Comment by sooroosh10** [comment]
Thank you. It works correctly.

**Comment by sooroosh10** [comment]
Hello again. I ran into another issue. I thought if I continued all the
tutorials this problem would be solved but it didn't. After the character
plays Rolling animation, an error happens and causes deformations on
character bones after performing jump animation.
I have attached a pic to show you the problem. Is there any way to solve
this issue?
best regards.
Farzami Sooroosh.

**Comment by AchimTuran** [comment]
Sadly the image seems not to be uploaded. So I don't know what is wrong. If it is still a additive base pose issue, I had some luck yesterday with UE5.0.3. There we seem not to have this issue.

**Comment by AchimTuran** [comment]
During my last retargeting session the additive base pose issue was gone. I used 5.0.3. 

If you still have the issue after updating to 5.0.3 feel free to reopen this issue and we can have a look at it again. 😉

**Comment by sooroosh10** [comment]
this is the image

**Comment by AchimTuran** [comment]
Some bugs in that area are fixed for UE5.1 and I also recorded some videos on how to fix those issues. 
https://youtube.com/playlist?list=PLslFX7TZAr88H2njZ6wYDoL3PPcsEJ7t2
