### ISSUE TITLE
[Feature Request] 5.3 support

### ISSUE THREAD

**Issue by kostenickj** [tuatec/TTToolbox#47]
Will this plugin be updated to work with UE 5.3? Looks like there were a lot of changes to how animation curves work and it no longer compiles.

**Comment by JonnyDotNet** [comment]
I second this request and am willing to help if required.

**Comment by AchimTuran** [comment]
Epics made breaking changes for IKRig, Blutilities and AnimCurves. So not sure when 5.3 will be fully supported.

Started to work in #48. As the blueprint scripting world seems to be unstable and it's to much effort to support multiple version of the engine I will port everything to C++. With this approach it will be possible to support two or three engine versions at the same time without having to deal with Binary files int Git. But this might take some time...

**Comment by b7r3333** [comment]
gggv

**Comment by themaoci** [comment]
Tried to compile the ue 5.3 version but for some reason it crashed for me on android.automation.dll maybe i messed something up... Could someone release this tool compuled for 5.3 unreal ? Thanks.

**Comment by kapkrash** [comment]
Just for clarification. I followed the Youtube Guide where I made it from 0 to 10 without needing to cross-reference this repo branch by following youtube guide and double-checking comments. There were a couple fix actions done because of youtube comments., which I thought was easier to follow due to they're time references helped guide me where I needed to go. Also I used Rider, and On 11 it was clear that Deprecation issues required refactoring. 

as for your comment @themaoci I noticed that when I used "#if WITH_EDITOR" early in following the guide, the IDE auto added the header file for android instead of what was used by the toolkit. 
#include "HAL/PlatformApplicationMisc.h"
